replicaCount: 1

image:
  repositoryUrl: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
  tag: v0.10.4
  pullPolicy: IfNotPresent
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  periodSeconds: 10
  grpc:
    port: 50051

livenessProbe:
  periodSeconds: 10
  grpc:
    port: 50051

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  grpc:
    port: 50051

pvc:
  create: false
configmap:
  create: false
secret:
  create: false

env:
  PORT: "50051"
  DISABLE_PROFILER: "1"
