replicaCount: 1

image:
  repositoryUrl: redis
  tag: alpine
  pullPolicy: IfNotPresent
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379

command:
  - redis-server

args:
  - "--save"
  - ""
  - "--appendonly"
  - "no"
  - "--stop-writes-on-bgsave-error"
  - "no"
  - "--dir"
  - "/data"

resources:
  requests:
    cpu: 70m
    memory: 200Mi
  limits:
    cpu: 125m
    memory: 256Mi

readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  tcpSocket:
    port: 6379

livenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  tcpSocket:
    port: 6379

startupProbe:
  failureThreshold: 30
  periodSeconds: 10
  tcpSocket:
    port: 6379

pvc:
  volumes:
    - name: redis-data
      emptyDir: {}
  volumeMounts:
    - name: redis-data
      mountPath: /data
