replicaCount: 1

image:
  repositoryUrl: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
  tag: v0.10.4
  pullPolicy: IfNotPresent
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  periodSeconds: 5
  grpc:
    port: 8080

livenessProbe:
  periodSeconds: 5
  grpc:
    port: 8080

startupProbe:
  failureThreshold: 30
  periodSeconds: 5
  grpc:
    port: 8080

pvc:
  create: false
configmap:
  create: false
secret:
  create: false

env:
  PORT: "8080"
  DISABLE_PROFILER: "1"
