replicaCount: 1

image:
  repositoryUrl: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  tag: v0.10.4
  pullPolicy: IfNotPresent
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555

resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi

readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  grpc:
    port: 9555

livenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  grpc:
    port: 9555

startupProbe:
  periodSeconds: 10
  failureThreshold: 30
  grpc:
    port: 9555

pvc:
  create: false
configmap:
  create: false
secret:
  create: false

env:
  PORT: "9555"
