replicaCount: 1

# annotationExtra:
#   sidecar.istio.io/rewriteAppHTTPProbers: "true"

image:
  repositoryUrl: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
  tag: v0.10.4
  pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  periodSeconds: 10
  httpGet:
    path: /_healthz
    port: 8080
    httpHeaders:
      - name: Cookie
        value: shop_session-id=x-readiness-probe

livenessProbe:
  periodSeconds: 10
  httpGet:
    path: /_healthz
    port: 8080
    httpHeaders:
      - name: Cookie
        value: shop_session-id=x-liveness-probe

startupProbe:
  httpGet:
    path: /_healthz
    port: 8080
  failureThreshold: 30
  periodSeconds: 10

pvc:
  create: false
configmap:
  create: false
secret:
  create: false

env:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog-service.productcatalog:3550"
  CURRENCY_SERVICE_ADDR: "currency-service.currency:7000"
  CART_SERVICE_ADDR: "cart-apps-service.cart:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice.recommendation:8080"
  SHIPPING_SERVICE_ADDR: "shipping-service.shipping:50051"
  CHECKOUT_SERVICE_ADDR: "checkout-service.checkout:5050"
  AD_SERVICE_ADDR: "adservice.ads:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice.shoppingassistantservice:80"
  ENABLE_PROFILER: "0"
