replicaCount: 1

image:
  repositoryUrl: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
  tag: v0.10.4
  pullPolicy: IfNotPresent
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  grpc:
    port: 3550

livenessProbe:
  grpc:
    port: 3550

pvc:
  create: false

configmap:
  create: false

secret:
  create: false

env:
  PORT: "3550"
  DISABLE_PROFILER: "1"
